### ISSUE TITLE
Support for Multiple Sinks

### ISSUE THREAD

**Issue by eytan-avisror** [heptiolabs/eventrouter#79]
Readme mentions one of the goals of this project is `Support for multiple sinks should be configurable`, but looking at the code I don't see that it currently supports using multiple sinks.
It would be good to support this, for example stdout + s3sink.

the configuration json object should parse a list instead of a string, for example:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: eventrouter
  namespace: eventrouter
data:
  config.json: |-
    {
      "sink": ["stdout", "s3sink"]
    }
```

Am I missing something? is this currently somehow possible?
